import { Layers3, ListOrdered, Send, ShieldCheck, Undo2, X } from 'lucide-react'
import LoadingSpinner from '../common/LoadingSpinner'
const formatDate=value=>{if(!value)return '-';const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString()}
function PackageDetailModal({isOpen,response,isLoading,isStatusSaving,onClose,onManageCategories,onManageQuestions,onManageTiers,onPublish,onUnpublish}) {
 if(!isOpen)return null; const item=response?.data
 return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-2xl bg-white shadow-xl">
  <div className="sticky top-0 z-10 flex items-center justify-between border-b bg-white px-6 py-4"><div><h2 className="text-xl font-semibold text-gray-900">Package Detail</h2><p className="text-sm text-gray-500">Review mappings and publication status.</p></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-gray-500 hover:bg-gray-100"><X size={20}/></button></div>
  {isLoading?<div className="flex min-h-64 items-center justify-center"><LoadingSpinner/></div>:!item?<div className="p-6 text-sm text-red-600">Unable to load package detail.</div>:<div className="space-y-6 p-6">
   <section className="rounded-xl border p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="text-lg font-semibold text-gray-900">{item.name}</h3><p className="mt-1 text-sm text-gray-500">{item.slug}</p></div><div className="flex items-center gap-2"><span className={`rounded-full px-3 py-1 text-xs font-medium capitalize ${item.status==='published'?'bg-green-100 text-green-700':'bg-gray-100 text-gray-700'}`}>{item.status}</span>{item.status==='published'?<button disabled={isStatusSaving} onClick={onUnpublish} className="inline-flex items-center gap-2 rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium hover:bg-gray-50 disabled:opacity-50"><Undo2 size={16}/> Unpublish</button>:<button disabled={isStatusSaving} onClick={onPublish} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-sm font-medium text-white hover:bg-blue-700 disabled:opacity-50"><Send size={16}/> Publish</button>}</div></div><p className="mt-4 text-sm text-gray-700">{item.description||'-'}</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Duration" value={`${item.durationMinutes} minutes`}/><Info label="Questions" value={item.questionCount??0}/><Info label="Passing Score" value={item.passingScore??'-'}/><Info label="Access" value={item.isFree?'Free':'Paid'}/><Info label="Start At" value={formatDate(item.startAt)}/><Info label="End At" value={formatDate(item.endAt)}/></div></section>
   <Section title="Categories" icon={Layers3} action="Manage Categories" onAction={onManageCategories}>{(item.categories||[]).length?(item.categories||[]).map(c=><span key={c.id} className="rounded-lg bg-gray-100 px-3 py-2 text-sm">{c.name}</span>):<Empty text="No categories assigned."/>}</Section>
   <Section title="Questions" icon={ListOrdered} action="Manage Questions" onAction={onManageQuestions}><div className="w-full space-y-2">{(item.questions||[]).length?(item.questions||[]).map((q,i)=><div key={q.id} className="rounded-lg bg-gray-50 p-3 text-sm"><b className="mr-2">{q.questionOrder??i+1}.</b>{q.questionText||'-'}</div>):<Empty text="No questions assigned."/>}</div></Section>
   <Section title="Subscription Tiers" icon={ShieldCheck} action="Manage Access" onAction={onManageTiers}>{(item.subscriptionTiers||[]).length?(item.subscriptionTiers||[]).map(t=><span key={t.id} className="rounded-lg bg-gray-100 px-3 py-2 text-sm">{t.name} · {t.price}</span>):<Empty text="No subscription tiers assigned."/>}</Section>
  </div>}
 </div></div>
}
function Info({label,value}){return <div><p className="text-xs font-medium uppercase text-gray-400">{label}</p><p className="mt-1 text-sm font-medium text-gray-800">{value}</p></div>}
function Empty({text}){return <p className="text-sm text-gray-500">{text}</p>}
function Section({title,icon:Icon,action,onAction,children}){return <section className="rounded-xl border p-5"><div className="flex items-center justify-between gap-3"><h3 className="flex items-center gap-2 font-semibold text-gray-900"><Icon size={18}/>{title}</h3><button type="button" onClick={onAction} className="rounded-lg border border-gray-300 px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50">{action}</button></div><div className="mt-3 flex flex-wrap gap-2">{children}</div></section>}
export default PackageDetailModal
